<?php

declare(strict_types=1);

namespace App\Support\Theme;

/**
 * Turns a single admin-picked hex color into a full Tailwind-style 50-900
 * shade ramp, and renders it as CSS custom-property overrides.
 *
 * The picked color is reproduced exactly at shade 600 — the stop primary
 * buttons and active nav states use — so "I picked X" visibly means "the
 * app's primary color is X", not an approximation of it. Every other stop is
 * generated by interpolating lightness from that anchor out towards a near-
 * white cap (shade 50) or a near-black floor (shade 900), so the ramp always
 * has full contrast range regardless of how light or dark the pick is. The
 * anchor lightness is clamped to a working mid-range first: an admin picking
 * something already near-white or near-black would otherwise invert the
 * interpolation (lighter shades ending up darker than the anchor, etc.).
 */
class BrandPalette
{
    public const string DEFAULT_COLOR = '#4f46e5';

    /**
     * @var array<string, string>
     */
    public const array PRESETS = [
        'Indigo' => '#4f46e5',
        'Violet' => '#7c3aed',
        'Fuchsia' => '#c026d3',
        'Rose' => '#e11d48',
        'Amber' => '#d97706',
        'Emerald' => '#059669',
        'Teal' => '#0d9488',
        'Sky' => '#0284c7',
    ];

    private const int ANCHOR_SHADE = 600;

    private const float LIGHT_CAP = 97.0;

    private const float DARK_FLOOR = 16.0;

    private const float ANCHOR_MIN = 28.0;

    private const float ANCHOR_MAX = 70.0;

    /**
     * @var array<int, float> shade => default lightness (0-100) when the
     *                        anchor sits at its own default (42, shade 600)
     */
    private const array LIGHTNESS_CURVE = [
        50 => 97.0,
        100 => 94.0,
        200 => 86.0,
        300 => 74.0,
        400 => 60.0,
        500 => 50.0,
        600 => 42.0,
        700 => 34.0,
        800 => 28.0,
        900 => 20.0,
    ];

    /**
     * @return array<int, string> shade => hex, keyed 50..900
     */
    public static function ramp(?string $hex): array
    {
        [$h, $s, $inputLightnessFraction] = self::hexToHsl(self::sanitize($hex));
        $inputLightness = $inputLightnessFraction * 100;

        $anchorLightness = min(self::ANCHOR_MAX, max(self::ANCHOR_MIN, $inputLightness));
        $anchorDefault = self::LIGHTNESS_CURVE[self::ANCHOR_SHADE];

        $ramp = [];

        foreach (self::LIGHTNESS_CURVE as $shade => $default) {
            $lightness = match (true) {
                $shade === self::ANCHOR_SHADE => $anchorLightness,
                $default > $anchorDefault => self::interpolate($default, $anchorDefault, self::LIGHT_CAP, $anchorLightness),
                default => self::interpolate($default, $anchorDefault, self::DARK_FLOOR, $anchorLightness),
            };

            // The very deepest stop gets a touch less saturation so it reads
            // as rich rather than neon.
            $shadeSaturation = $shade >= 900 ? $s * 0.9 : $s;

            $ramp[$shade] = self::hslToHex($h, $shadeSaturation, $lightness);
        }

        return $ramp;
    }

    /**
     * Linearly maps a stop's default curve position onto the actual ramp
     * being built: $default === $anchorDefault yields $anchorLightness,
     * $default at the far end of its side (0 or 100) yields $boundLightness,
     * and everything between is proportional — so the curve's original
     * relative spacing between stops is preserved either side of the anchor.
     */
    private static function interpolate(float $default, float $anchorDefault, float $boundLightness, float $anchorLightness): float
    {
        $ratio = $default > $anchorDefault
            ? ($default - $anchorDefault) / (100.0 - $anchorDefault)
            : ($anchorDefault - $default) / $anchorDefault;

        return $anchorLightness + $ratio * ($boundLightness - $anchorLightness);
    }

    /**
     * CSS custom-property declarations for :root, e.g. "--color-brand-500: #...;".
     */
    public static function cssVariables(?string $hex): string
    {
        $declarations = collect(self::ramp($hex))
            ->map(fn (string $value, int $shade): string => "--color-brand-{$shade}: {$value};")
            ->implode('');

        return ":root{{$declarations}}";
    }

    public static function isValidHex(string $hex): bool
    {
        return (bool) preg_match('/^#[0-9a-fA-F]{6}$/', $hex);
    }

    private static function sanitize(?string $hex): string
    {
        return $hex !== null && self::isValidHex($hex) ? $hex : self::DEFAULT_COLOR;
    }

    /**
     * @return array{0: float, 1: float, 2: float} hue (0-360), saturation (0-1), lightness (0-1)
     */
    private static function hexToHsl(string $hex): array
    {
        $hex = ltrim($hex, '#');

        $r = hexdec(substr($hex, 0, 2)) / 255;
        $g = hexdec(substr($hex, 2, 2)) / 255;
        $b = hexdec(substr($hex, 4, 2)) / 255;

        $max = max($r, $g, $b);
        $min = min($r, $g, $b);
        $l = ($max + $min) / 2;

        if ($max === $min) {
            return [0.0, 0.0, $l];
        }

        $d = $max - $min;
        $s = $l > 0.5 ? $d / (2 - $max - $min) : $d / ($max + $min);

        $h = match ($max) {
            $r => fmod(($g - $b) / $d, 6),
            $g => ($b - $r) / $d + 2,
            default => ($r - $g) / $d + 4,
        };

        $h *= 60;

        if ($h < 0) {
            $h += 360;
        }

        return [$h, $s, $l];
    }

    /**
     * @param  float  $h  hue (0-360)
     * @param  float  $s  saturation (0-1)
     * @param  float  $lPercent  lightness (0-100)
     */
    private static function hslToHex(float $h, float $s, float $lPercent): string
    {
        $h /= 360;
        $l = $lPercent / 100;

        if ($s === 0.0) {
            $r = $g = $b = $l;
        } else {
            $q = $l < 0.5 ? $l * (1 + $s) : $l + $s - $l * $s;
            $p = 2 * $l - $q;

            $r = self::hueToRgb($p, $q, $h + 1 / 3);
            $g = self::hueToRgb($p, $q, $h);
            $b = self::hueToRgb($p, $q, $h - 1 / 3);
        }

        return sprintf('#%02x%02x%02x', (int) round($r * 255), (int) round($g * 255), (int) round($b * 255));
    }

    private static function hueToRgb(float $p, float $q, float $t): float
    {
        if ($t < 0) {
            $t += 1;
        }

        if ($t > 1) {
            $t -= 1;
        }

        if ($t < 1 / 6) {
            return $p + ($q - $p) * 6 * $t;
        }

        if ($t < 1 / 2) {
            return $q;
        }

        if ($t < 2 / 3) {
            return $p + ($q - $p) * (2 / 3 - $t) * 6;
        }

        return $p;
    }
}
